spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://35.240.242.176:5432/shop_db
    username: '{cipher}cb149f3fb4e5611382132c16617c52d7f0b604d6b8c3fed1e4433b9c5a2ffdce'
    password: '{cipher}9ea912480434f64cb60f47fb6cfc696a2a4c73ee0969a426479240c203aeb984'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  security:
    oauth2:
      resourceserver:
        jwt:
          #         https
          issuer-uri: https://keycloak.trade-wise.online/auth/realms/go-selling-api
          jwk-set-uri: https://keycloak.trade-wise.online/auth/realms/go-selling-api/protocol/openid-connect/certs
#          local
#          issuer-uri: http://localhost:1234/auth/realms/go-selling-api
#          jwk-set-uri: http://localhost:1234/auth/realms/go-selling-api/protocol/openid-connect/certs
eureka:
  client:
    serviceUrl:
      defaultZone: http://8.222.225.41:8761/eureka
keycloak:
  realm: go-selling-api
  resource: go-selling
  auth-server-url: https://keycloak.trade-wise.online/auth
  credentials:
    username: 'admin'
    password: 'admin'
    client-id: '{cipher}68cb01c2cb6cc09d52d307bb77df71dd6ea99df0449c664e7031b6cbb6529055'
    secret: '{cipher}5807f6195a8c82e7b84659a7f0a2fe0cff482c808748f1a45339b7f9ff16a59a3e1a4274e2a96271282d4af50bdd5faddd1c55e9fa5d6cf5076411d1c49e0d57'
    provider: secret
file:
  uploadPath: shop-service/src/main/resources/storage/
openapi:
  service:
    title: shop-service
    version: 1.0.0
    url: http://8.222.225.41:8080

springdoc:
  api-docs:
    path: /shop-service/v3/api-docs
  swagger-ui:
    oauth:
      realm: 'go-selling-api'
      client-id: '{cipher}68cb01c2cb6cc09d52d307bb77df71dd6ea99df0449c664e7031b6cbb6529055'
      clientSecret: '{cipher}5807f6195a8c82e7b84659a7f0a2fe0cff482c808748f1a45339b7f9ff16a59a3e1a4274e2a96271282d4af50bdd5faddd1c55e9fa5d6cf5076411d1c49e0d57'
    path: /shop-service/swagger-ui.html