spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://35.240.242.176:5432/chat_db
    username: '{cipher}cb149f3fb4e5611382132c16617c52d7f0b604d6b8c3fed1e4433b9c5a2ffdce'
    password: '{cipher}9ea912480434f64cb60f47fb6cfc696a2a4c73ee0969a426479240c203aeb984'
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          #         https
          issuer-uri: https://keycloak.trade-wise.online/auth/realms/go-selling-api
          jwk-set-uri: https://keycloak.trade-wise.online/auth/realms/go-selling-api/protocol/openid-connect/certs
#          local
#          issuer-uri: http://localhost:1234/auth/realms/go-selling-api
#          jwk-set-uri: http://localhost:1234/auth/realms/go-selling-api/protocol/openid-connect/certs
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
openapi:
  service:
    title: chat-service
    version: 1.0.0
    url: http://localhost:8080

springdoc:
  api-docs:
    path: /chat-service/v3/api-docs
  swagger-ui:
    path: /chat-service/swagger-ui.html