spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          #         https
          issuer-uri: https://keycloak.trade-wise.online/auth/realms/go-selling-api
          jwk-set-uri: https://keycloak.trade-wise.online/auth/realms/go-selling-api/protocol/openid-connect/certs
  #          local
  #          issuer-uri: http://localhost:1234/auth/realms/go-selling-api
  #          jwk-set-uri: http://localhost:1234/auth/realms/go-selling-api/protocol/openid-connect/certs
  mail:
    host: smtp.gmail.com
    port: 587
    username: gosellingproject@gmail.com
    password: mmlrtnqtokjctfgx
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable : true
            required : true
          from: contact@email.com
      from:
        name: Sak
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
keycloak:
  realm: go-selling-api
  resource: go-selling
  auth-server-url: https://keycloak.trade-wise.online/auth
  credentials:
    username: 'admin'
    password: 'admin'
    client-id: '{cipher}68cb01c2cb6cc09d52d307bb77df71dd6ea99df0449c664e7031b6cbb6529055'
    secret: '{cipher}5807f6195a8c82e7b84659a7f0a2fe0cff482c808748f1a45339b7f9ff16a59a3e1a4274e2a96271282d4af50bdd5faddd1c55e9fa5d6cf5076411d1c49e0d57'
    provider: secret
logging:
  level:
    org.springframework.web: debug
openapi:
  service:
    title: user-service
    version: 1.0.0
    url: http://localhost:8080

springdoc:
  api-docs:
    path: /user-service/v3/api-docs
  swagger-ui:
    oauth:
      realm: 'go-selling-api'
      client-id: '{cipher}68cb01c2cb6cc09d52d307bb77df71dd6ea99df0449c664e7031b6cbb6529055'
      clientSecret: '{cipher}5807f6195a8c82e7b84659a7f0a2fe0cff482c808748f1a45339b7f9ff16a59a3e1a4274e2a96271282d4af50bdd5faddd1c55e9fa5d6cf5076411d1c49e0d57'
    path: /user-service/swagger-ui.html